app:
  name: ui
  image:
    repository: onecx/onecx-document-ui
  routing:
    enabled: true
    path: /mfe/document/
  operator:
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: ./OneCXDocumentModule
          description: OneCX Document UI
          note: OneCX Document UI auto import via MF operator
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-document
          tagName: onecx-document-component
          endpoints:
            - name: Document search
              path: /document
            - name: Document quick upload
              path: /document/quick-upload
            - name: Document create
              path: /document/create-document
            - name: Document details
              path: /document/details/{documentId}
            - name: Document type search
              path: /document/document-types
    permission:
      enabled: true
      spec:
        permissions:
          DOCUMENT:
            CREATE: Create documents
            EDIT: Edit documents
            DELETE: Delete document data
            SEARCH: Search documents
            VIEW: View document details
